// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using SupportTicketTriage.Infrastructure.Persistence;

#nullable disable

namespace SupportTicketTriage.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SupportTicketTriageDbContext))]
    [Migration("20261006092731_AddTicketReviews")]
    partial class AddTicketReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SupportTicketTriage.Domain.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ChatModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RedactedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RedactionVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("SelfReportedScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("TicketClassifications", (string)null);
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChatModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("CitationsValid")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DraftText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvalidCitationCount")
                        .HasColumnType("integer");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RedactionVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("TicketDrafts", (string)null);
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketDraftSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<double>("Similarity")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SourceTicketId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasCited")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SourceTicketId");

                    b.HasIndex("DraftId", "SourceTicketId")
                        .IsUnique();

                    b.ToTable("TicketDraftSources", (string)null);
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RedactedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RedactionVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId", "EmbeddingModel")
                        .IsUnique();

                    b.ToTable("TicketEmbeddings", (string)null);
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FinalText")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TicketDraftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasEdited")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TicketDraftId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("TicketReviews", (string)null);
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketRoutingDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("ClassificationScore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailedGates")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDraftEligible")
                        .HasColumnType("boolean");

                    b.Property<double>("MinimumClassificationScore")
                        .HasColumnType("double precision");

                    b.Property<double>("MinimumSimilarity")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<double?>("TopSimilarity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TicketId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("TicketRoutingDecisions", (string)null);
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketClassification", b =>
                {
                    b.HasOne("SupportTicketTriage.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketDraft", b =>
                {
                    b.HasOne("SupportTicketTriage.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketDraftSource", b =>
                {
                    b.HasOne("SupportTicketTriage.Infrastructure.Persistence.TicketDraft", null)
                        .WithMany("Sources")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupportTicketTriage.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("SourceTicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketEmbedding", b =>
                {
                    b.HasOne("SupportTicketTriage.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketReview", b =>
                {
                    b.HasOne("SupportTicketTriage.Infrastructure.Persistence.TicketDraft", null)
                        .WithMany()
                        .HasForeignKey("TicketDraftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SupportTicketTriage.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketRoutingDecision", b =>
                {
                    b.HasOne("SupportTicketTriage.Domain.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SupportTicketTriage.Infrastructure.Persistence.TicketDraft", b =>
                {
                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
